using System;
using UnityEngine;

namespace DG.Tweening.Core
{
	// Token: 0x02000047 RID: 71
	public static class Debugger
	{
		// Token: 0x06000241 RID: 577 RVA: 0x0000D088 File Offset: 0x0000B288
		public static void Log(object message)
		{
			Debug.Log("DOTWEEN :: " + message);
		}

		// Token: 0x06000242 RID: 578 RVA: 0x0000D09A File Offset: 0x0000B29A
		public static void LogWarning(object message)
		{
			Debug.LogWarning("DOTWEEN :: " + message);
		}

		// Token: 0x06000243 RID: 579 RVA: 0x0000D0AC File Offset: 0x0000B2AC
		public static void LogError(object message)
		{
			Debug.LogError("DOTWEEN :: " + message);
		}

		// Token: 0x06000244 RID: 580 RVA: 0x0000D0BE File Offset: 0x0000B2BE
		public static void LogReport(object message)
		{
			Debug.Log("<color=#00B500FF>DOTWEEN :: " + message + "</color>");
		}

		// Token: 0x06000245 RID: 581 RVA: 0x0000D0D5 File Offset: 0x0000B2D5
		public static void LogInvalidTween(Tween t)
		{
			Debugger.LogWarning("This Tween has been killed and is now invalid");
		}

		// Token: 0x06000246 RID: 582 RVA: 0x0000D0E1 File Offset: 0x0000B2E1
		public static void LogNestedTween(Tween t)
		{
			Debugger.LogWarning("This Tween was added to a Sequence and can't be controlled directly");
		}

		// Token: 0x06000247 RID: 583 RVA: 0x0000D0ED File Offset: 0x0000B2ED
		public static void LogNullTween(Tween t)
		{
			Debugger.LogWarning("Null Tween");
		}

		// Token: 0x06000248 RID: 584 RVA: 0x0000D0F9 File Offset: 0x0000B2F9
		public static void LogNonPathTween(Tween t)
		{
			Debugger.LogWarning("This Tween is not a path tween");
		}

		// Token: 0x06000249 RID: 585 RVA: 0x0000D105 File Offset: 0x0000B305
		public static void LogMissingMaterialProperty(string propertyName)
		{
			Debugger.LogWarning(string.Format("This material doesn't have a {0} property", propertyName));
		}

		// Token: 0x0600024A RID: 586 RVA: 0x0000D117 File Offset: 0x0000B317
		public static void LogRemoveActiveTweenError(string propertyName)
		{
			Debugger.Log(string.Format("Error in RemoveActiveTween.{0}. It's been taken care of so no problems, but Daniele (DOTween's author) is trying to pinpoint it and it would be awesome if you could reproduce this log in a sample project and send it to him. Or even just write him the complete log that was generated by this message. Fixing this would make DOTween slightly faster. Thanks.", propertyName));
		}

		// Token: 0x0600024B RID: 587 RVA: 0x0000D129 File Offset: 0x0000B329
		public static void SetLogPriority(LogBehaviour logBehaviour)
		{
			if (logBehaviour == LogBehaviour.Default)
			{
				Debugger.logPriority = 1;
				return;
			}
			if (logBehaviour != LogBehaviour.Verbose)
			{
				Debugger.logPriority = 0;
				return;
			}
			Debugger.logPriority = 2;
		}

		// Token: 0x04000117 RID: 279
		public static int logPriority;
	}
}
